[project]
name = "LLSIFTeamBuilder"
version = "0.0.1"
description = "Simulation environment and team builder for LLSIF"
requires-python = ">=3.10"
dependencies = ["numpy >=2.31"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"